#!/bin/sh
set -e -x
# gh repo create <repo> --private --clone
# gh repo create <owner>/<repo> --private --clone

REPO=$1

if [ "$REPO" != "" ];
then
  # check if the repo's format is <owner>/<repo>
  if echo "$REPO" | grep -q "/"; then
    echo "Creating repository $REPO"
    ghq create https://githb.com/${REPO}
    cd $(ghq root)/github.com/${REPO}
git init
  else
    ghq create https://github.com/yokawasa/${REPO}
    cd $(ghq root)/github.com/yokawasa/${REPO}
  fi
  echo "Initialized empty Git repository in $(pwd)"
  git init
  # create initial README.md file 
  echo "# $REPO" > README.md
  git add README.md
  git commit -m "Initial commit"
  gh repo create --private --source=. --remote=origin --push
else
  echo "$0 <repo>"
fi
exit 0
