#!/bin/sh

if [ $# -ne 1 ]
then
  echo "$0 [json file]"
  echo "   yq - Command-line YAML processor" 1>&2
  echo "        See https://github.com/kislyuk/yq for the installation" 1>&2
  exit 1
fi

if ! command -v yq > /dev/null; then
  echo "NOT yq installed"
  echo "Please install yq"
  echo "   yq - Command-line YAML processor" 1>&2
  echo "        See https://github.com/kislyuk/yq for the installation" 1>&2
  echo " macOS> brew install python-yq"
  exit 1
fi

cat $1 | yq -y


